### PR TITLE
Allow `Printer` tests to succeed on Windows in `tox`

### LINKED ISSUE #1249: When Tests are Run in `tox` on Windows, the `Printer` Tests Fail
### Describe the bug

Running `tox -e py -- tests\console\test_Printer.py` on Windows in PowerShell or CMD fails. (This failure doesn't happen in git bash.)

```
py: commands[0]> python -m coverage run -m pytest tests\console\test_Printer.py
================================================= test session starts =================================================
platform win32 -- Python 3.11.3, pytest-7.3.1, pluggy-1.0.0
cachedir: .tox\py\.pytest_cache
rootdir: C:\Users\user\github\beeware\briefcase
configfile: pyproject.toml
plugins: xdist-3.2.1
collected 5 items

tests\console\test_Printer.py FF.FF                                                                              [100%]

====================================================== FAILURES =======================================================
_________________________________ test_call[True-a line of output-a line of output\n] _________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x0000024FE79D6D50>
printer = <briefcase.console.Printer object at 0x0000024FE79E74D0>, message = 'a line of output', show = True
expected_console_output = 'a line of output\n'

    @pytest.mark.parametrize(
        "show, message, expected_console_output",
        [
            (True, "a line of output", "a line of output\n"),
            (False, "a line of output", ""),
        ],
    )
    def test_call(capsys, printer, message, show, expected_console_output):
        """Printer prints to console and log appropriately."""
        printer(message, show=show, stack_offset=1)
        assert capsys.readouterr().out == expected_console_output
        log = printer.export_log()
        assert len(log.splitlines()) == 1
>       assert " " + message + " " * 139 + "console.py" in log
E       AssertionError: assert (((' ' + 'a line of output') + (' ' * 139)) + 'console.py') in '[20:49:40] a line of output
                    console.py:108\n'

tests\console\test_Printer.py:28: AssertionError
_________________________________________ test_call[False-a line of output-] __________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x0000024FE79FAA50>
printer = <briefcase.console.Printer object at 0x0000024FE79FBE90>, message = 'a line of output', show = False
expected_console_output = ''

    @pytest.mark.parametrize(
        "show, message, expected_console_output",
        [
            (True, "a line of output", "a line of output\n"),
            (False, "a line of output", ""),
        ],
    )
    def test_call(capsys, printer, message, show, expected_console_output):
        """Printer prints to console and log appropriately."""
        printer(message, show=show, stack_offset=1)
        assert capsys.readouterr().out == expected_console_output
        log = printer.export_log()
        assert len(log.splitlines()) == 1
>       assert " " + message + " " * 139 + "console.py" in log
E       AssertionError: assert (((' ' + 'a line of output') + (' ' * 139)) + 'console.py') in '           a line of output
                    console.py:108\n'

tests\console\test_Printer.py:28: AssertionError
_____________________________________________________ test_to_log _____________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x0000024FE7A52790>
printer = <briefcase.console.Printer object at 0x0000024FE7A50490>

    def test_to_log(capsys, printer):
        """Printer prints only to log."""
        printer.to_log("a line of output", stack_offset=1)
        assert capsys.readouterr().out == ""
        log = printer.export_log()
        assert len(log.splitlines()) == 1
>       assert " a line of output" + " " * 139 + "console.py" in log
E       AssertionError: assert ((' a line of output' + (' ' * 139)) + 'console.py') in '           a line of output     
             console.py:108\n'

tests\console\test_Printer.py:44: AssertionError
_________________________________________________ test_very_long_line _________________________________________________

capsys = <_pytest.capture.CaptureFixture object at 0x0000024FE7A56C50>
printer = <briefcase.console.Printer object at 0x0000024FE7A57250>

    def test_very_long_line(capsys, printer):
        """Very long lines are split."""
        printer.to_log("A very long line of output!! " * 6, stack_offset=1)
        assert capsys.readouterr().out == ""
        log = printer.export_log()
        assert len(log.splitlines()) == 2
>       assert (" " + "A very long line of output!! " * 5 + "A very    console.py:") in log
E       AssertionError: assert ((' ' + ('A very long line of output!! ' * 5)) + 'A very    console.py:') in '
A very long line of output!! A very long line of output!! A very long line of output!! A very long line of...
                                                                                                         \n'

tests\console\test_Printer.py:53: AssertionError
=============================================== short test summary info ===============================================
FAILED tests/console/test_Printer.py::test_call[True-a line of output-a line of output\n] - AssertionError: assert ((...
FAILED tests/console/test_Printer.py::test_call[False-a line of output-] - AssertionError: assert (((' ' + 'a line of...
FAILED tests/console/test_Printer.py::test_to_log - AssertionError: assert ((' a line of output' + (' ' * 139)) + 'co...
FAILED tests/console/test_Printer.py::test_very_long_line - AssertionError: assert ((' ' + ('A very long line of outp...
============================================= 4 failed, 1 passed in 0.12s =============================================
```

However, `pytest -vv tests\console\test_Printer.py` works fine...

```
❯ pytest -vv tests\console\test_Printer.py
platform win32 -- Python 3.11.3
pytest==7.3.1
pluggy==1.0.0
rootdir: C:\Users\user\github\beeware\briefcase
inifile: pyproject.toml
plugins: tldr-0.2.5, xdist-3.2.1
cachedir: .pytest_cache

------------------------------------------------------------------------------
tests/console/test_Printer.py::test_call[True-a line of output-a line of output\n] ... ok
tests/console/test_Printer.py::test_call[False-a line of output-] ... ok
tests/console/test_Printer.py::test_to_console ... ok
tests/console/test_Printer.py::test_to_log ... ok
tests/console/test_Printer.py::test_very_long_line ... ok

------------------------------------------------------------------------------
Ran 5 tests in 0.03s

OK
```

### Steps to reproduce

Run `tox -e py` on Windows in PowerShell or CMD.

### Expected behavior

Tests pass.

### Screenshots

_No response_

### Environment

- Operating System: Windows 11 22H2
- Python version: Python 3.11/10 (winstore or otherwise)
- Software versions:
  - Briefcase: `0.3.14`, `0.3.15.dev148+gda62b7c5`

### Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rmartin16**
## Changes
- Fixes #1249

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Can't argue that this will let the tests pass; however, my concern is what it could potentially mask. It's effectively removing *all* spaces from the comparison text - which means if the output completely eats spaces, the test will pass.

Would it be better to use a `re.sub("\s{100,}", " " * 100)` (or similar), so that "100 or more spaces" are normalised to "100 spaces"? That would address the specific spacing inconsistency we're seeing, rather than eating *all* spacing.

**Comment by rmartin16** [comment]
hmm....`test_very_long_line` test is failing. It only has a few characters between the log message and the filename. let me see.

**Comment by rmartin16** [comment]
Also...just FYI if it comes up:

When running `tox` with Python 3.8 or 3.9 on Windows, if `tox` evaluates using a Windows Store version of Python, it will crash when calling `Path().resolve()` on the "shortcut" to the actual exe. This was seemingly resolved in 3.10+.

```
❯ tox -vve py311
.pkg: 640 I find interpreter for spec PythonSpec(path=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe) [virtualenv\discovery\builtin.py:58]
.pkg: 640 D got python info of C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\python.exe from C:\Users\user\AppData\Local\pypa\virtualenv\py_info\1\f898549b12c94c37efbe1de61015c8cafd30c69957abb1f323e6eb19f963fc36.json [virtualenv\app_data\via_disk_folder.py:131]
.pkg: 843 I proposed PythonInfo(spec=CPython3.8.10.final.0-64, system=C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\python.exe, exe=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe, platform=win32, version='3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:65]
.pkg: 843 D accepted PythonInfo(spec=CPython3.8.10.final.0-64, system=C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\python.exe, exe=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe, platform=win32, version='3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:67]
.pkg: 843 D symlink on filesystem does not work [virtualenv\info.py:45]
.pkg: 843 D filesystem is not case-sensitive [virtualenv\info.py:26]
.pkg: 890 I find interpreter for spec PythonSpec(path=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe) [virtualenv\discovery\builtin.py:58]
.pkg: 890 I proposed PythonInfo(spec=CPython3.8.10.final.0-64, system=C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\python.exe, exe=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe, platform=win32, version='3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:65]
.pkg: 890 D accepted PythonInfo(spec=CPython3.8.10.final.0-64, system=C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\python.exe, exe=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe, platform=win32, version='3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:67]
py311: 890 I find interpreter for spec PythonSpec(major=3, minor=11) [virtualenv\discovery\builtin.py:58]
py311: 890 I proposed PythonInfo(spec=CPython3.8.10.final.0-64, system=C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\python.exe, exe=C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\Scripts\python.exe, platform=win32, version='3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:65]
py311: 890 D got python info of C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\python3.11.exe from C:\Users\user\AppData\Local\pypa\virtualenv\py_info\1\bc0e72d759aaff9877b1c8f03deffc8790a035bb414afe833bd110de92881dba.json [virtualenv\app_data\via_disk_folder.py:131]
py311: 1093 D got python info of C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe from C:\Users\user\AppData\Local\pypa\virtualenv\py_info\1\380ed02cd77d25ac9094f63fa5ba747f216de5a39fbe725b5ea70f71d9d98694.json [virtualenv\app_data\via_disk_folder.py:131]
py311: 1328 I proposed Pep514PythonInfo(spec=CPython3.11.3.final.0-64, system=C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe, exe=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\python3.11.exe, platform=win32, version='3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:65]
py311: 1328 D accepted Pep514PythonInfo(spec=CPython3.11.3.final.0-64, system=C:\Users\user\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe, exe=C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\python3.11.exe, platform=win32, version='3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252) [virtualenv\discovery\builtin.py:67]
py311: 1328 E internal error [tox\session\cmd\run\single.py:58]
Traceback (most recent call last):
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\session\cmd\run\single.py", line 45, in _evaluate
    tox_env.setup()
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\api.py", line 249, in setup
    self._setup_env()
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\runner.py", line 106, in _setup_env
    super()._setup_env()
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\api.py", line 198, in _setup_env
    self.ensure_python_env()
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\api.py", line 202, in ensure_python_env
    conf = self.python_cache()
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 77, in python_cache
    base = super().python_cache()
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\api.py", line 240, in python_cache
    "version_info": list(self.base_python.version_info),
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\api.py", line 250, in base_python
    self._base_python = self._get_python(base_pythons)
  File "C:\Users\user\github\beeware\briefcase\venv-3.8.briefcase\lib\site-packages\tox\tox_env\python\virtual_env\api.py", line 143, in _get_python
    extra={"executable": Path(interpreter.system_executable).resolve()},
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\lib\pathlib.py", line 1181, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\user\.pyenv\pyenv-win\versions\3.8.10\lib\pathlib.py", line 206, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1920] The file cannot be accessed by the system: 'C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\python.exe'
  py311: FAIL code 2 (0.44 seconds)
  evaluation failed :( (1.16 seconds)
```

**Review by freakboy3742 — APPROVED** [review]
👍

**Pull request merged**
