### PR TITLE
Check for updates to `pre-commit` hooks every Sunday

### PR DESCRIPTION
**Pull request by rmartin16**
~~Waiting on `flake8-eradicate` to be updated for `flake8>=6`~~
~~- https://github.com/wemake-services/flake8-eradicate/pull/271~~

Updated `pre-commit` hooks and dropped support for `flake8-eradicate` due to extended incompatibility with `flake8==6.0.0`.

See beeware/.github#6 for details.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
@rmartin16 Is this ready to come out of draft? It looks like it should be up to date and ready to merge, but I wanted to check you haven't got something else in mind.

**Comment by rmartin16** [comment]
It could come out of draft....but the created PR couldn't be merged because `flake8-eradicate` doesn't have a release compatible with `flake8==6.0.0`. That's the case as well with a few other of these PRs.

**Comment by freakboy3742** [comment]
@rmartin16 So... there's been [an open PR](wemake-services/flake8-eradicate#271) to fix this problem since Dec 4; that doesn't seem to suggest they're particularly responsive as a project. While `flake8-eradicate` is a nice-to-have tool, I wouldn't call it essential. Would it be worth considering dropping it entirely (or, at least, dropping it for now, until such time as they release a version that is compatible)?

**Comment by mhsmith** [comment]
Does this workflow create separate PRs per requirement, like dependabot? If so, we can simply delay merging the flake8 bump until it's safe to do so.

**Comment by rmartin16** [comment]
@mhsmith: No, this workflow does not (presently) create separate PRs for each `pre-commit` hook. The basic mechanics are available to do this, though, since `pre-commit` supports updating a single hook via `pre-commit autoupdate --repo <REPO>`. From there, the repos for all the hooks would need to be enumerated and so forth....(I am mostly hoping that Dependabot adds support for `pre-commit` before doing all this :) )

I'm fine with dropping `flake8-eradicate` for now, though; commits inbound.

**Review by freakboy3742 — APPROVED** [review]
👍

**Pull request merged**
