### PR TITLE
Update contribute-code.rst

### PR DESCRIPTION
**Pull request by ChicagoDev**
Explicitly inform that Briefcase is run with the -m argument. Added troubleshooting step to add Briefcase to their Python path.

Novice contributors will have more detailed documentation on setting up their dev. environment

## PR Checklist:

- [ ] All new features have been tested
- [ X ] All new features have been documented
- [ X ] I have read the **CONTRIBUTING.md** file
- [ X ] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — COMMENTED** [review]
You shouldn't need to do any of this to make briefcase work. If you've done a `pip install -e .`, briefcase should be in your path; it should be installed as an extra, so the `python -m` option shouldn't be needed; and you *definitely* shouldn't need to do any `sys.path` wrangling.

**Comment by ChicagoDev** [comment]
Hmmm...

I have a terminal log that shows that I used pip install -e (Just double-checked)

image

**Comment by freakboy3742** [comment]
And having done that, `briefcase` by itself doesn't work?

**Comment by ChicagoDev** [comment]
No, not for me. I guess it could be a local configuration issue on my computer. 

`
(venv) blakegideon@Blakes-Air PycharmProjects % python3 briefcase
/Users/blakegideon/PycharmProjects/briefcase/venv/bin/python3: can't find '__main__' module in 'briefcase'
(venv) blakegideon@Blakes-Air PycharmProjects % briefcase
/Users/blakegideon/PycharmProjects/briefcase/venv/bin/python3: No module named /Users/blakegideon/PycharmProjects/briefcase/src/briefcase
(venv) blakegideon@Blakes-Air PycharmProjects % wpd
zsh: command not found: wpd
(venv) blakegideon@Blakes-Air PycharmProjects % pwd
/Users/blakegideon/PycharmProjects
(venv) blakegideon@Blakes-Air PycharmProjects % cd briefcase 
(venv) blakegideon@Blakes-Air briefcase % briefcase
/Users/blakegideon/PycharmProjects/briefcase/venv/bin/python3: No module named /Users/blakegideon/PycharmProjects/briefcase/src/briefcase
(venv) blakegideon@Blakes-Air briefcase % cd src
(venv) blakegideon@Blakes-Air src % briefcase
/Users/blakegideon/PycharmProjects/briefcase/venv/bin/python3: No module named /Users/blakegideon/PycharmProjects/briefcase/src/briefcase
(venv) blakegideon@Blakes-Air src % python3 briefcase
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "briefcase/__main__.py", line 3, in <module>
    from .cmdline import parse_cmdline
ImportError: attempted relative import with no known parent package
(venv) blakegideon@Blakes-Air src % python3 -m briefcase
usage: briefcase [-h] <command> [<platform>] [<format>] ...

Package Python code for distribution.

positional arguments:
  command        the command to execute (one of: new, dev, upgrade, create, update, build, run, package, publish)

optional arguments:
  -f, --formats  show the available output formats and exit (specify a platform for more details).
  -V, --version  show program's version number and exit

Each command, platform and format has additional options. Use the -h option on a specific command for more details.

(venv) blakegideon@Blakes-Air src % 

`

**Comment by ChicagoDev** [comment]
Since it doesn't belong in the documentation. Maybe I should add it on StackOverflow in case anyone else runs into the same issue

**Comment by freakboy3742** [comment]
I mean - I can't stop you... but in this case, I'm not sure what posting to StackOverflow will achieve. The problem you're having will almost certainly be specific to some oddity of your particular setup; I'm not sure how StackOverflow will help diagnose the problem; and frankly I'm petrified about suggestions like "just tweak sys.path" getting out there as advice, because that becomes one more thing I need to be aware of that people might have done to their environment when they report odd things going wrong.

I'd suggest that the BeeWare Discord chat would be a much more effective way to debug this, as it allows for a much faster turnaround in responses.

**Pull request closed without merging**
