### PR TITLE
Refs #718 - Modify AppImage builds to install dependencies from source

### PR DESCRIPTION
**Pull request by freakboy3742**
When building apps on Linux, users have reported errors of the form:

    libXXXX-<hash>.so.5.0.0: ELF load command address/offset not properly aligned

Apps that use Pillow are a common thread where this error is reported. in that instance, it's usually `libtiff` that raises the error (See #458, #618). 

These errors don't manifest when running on an Ubuntu 18.04 machine; they only appear when using a more recent machine (Ubuntu 22.04, Fedora 34).

I found [this comment from one of the linuxdeploy maintainers](https://github.com/linuxdeploy/linuxdeploy-plugin-conda/issues/39#issuecomment-792876427) which suggests there's something going on when the binary module is compiled. There's also [this comment on #458](https://github.com/beeware/briefcase/issues/458#issuecomment-1019271111) that suggests using an older version of Pillow will fix the error.

That led me to wonder if the issue is something about the interaction of manylinux binary wheels and Linuxdeploy. It's unlikely that an older version of Pillow would be doing anything radically different... but an older version of Pillow *would* be compiled from source, rather than being installed from a precompiled binary manylinux wheel.  

My testing has shown that installing all dependencies from source appears to fix the problem. This does impose the requirement that end-users need to specify more requirements in `system-requires`; and builds take longer (because all the binary modules need to be compiled); but... they *work*.

A little more investigation reveals that part of producing a ``manylinux`` wheel is running a tool called ``auditwheel`` - which does some library relocations that are similar to what linuxdeploy is doing (AFAICT).

So: this PR modifies the AppImage tooling to add `--no-binary :all:` to the arguments passed to pip install. This rejects binary wheels as an option, forcing all Python dependencies to be build from source.

It also modifies the `update` command on the AppImage backend so that it correctly inherits Docker wrapping behaviour (as well as the new pip argument handling). This would have led to incorrect behaviour if anyone tried to run `update` on a Linux app.

Tested was performed with the [Python support testbed](https://github.com/beeware/Python-support-testbed) project. This primarily exercises Pillow as a test case for this problem. The testbed will fail on the GTK family of tests without also using #756 - but the Pillow tests will pass. Without this patch, you get the "ELF load command address/offset not properly aligned" error on `libtiff` when PIL is imported.

I built the test AppImage on a macOS x86_64 machine in Docker. The AppImage worked on a Parallels install of:
* Ubuntu 18.04
* Ubuntu 22.04
* Fedora 34

Without this patch, the AppImage would work on Ubuntu 18.04, but fail on Ubuntu 22.04 and Fedora 34.
 
## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by freakboy3742** [comment]
Whelp... that's annoying. Pyside2 and Pyside6 are *only* available as binary wheels.

Back to the drawing board, I guess...

**Comment by danyeaw** [comment]
> Whelp... that's annoying. Pyside2 and Pyside6 are _only_ available as binary wheels.

Drat! That was a good idea to explore.

**Comment by freakboy3742** [comment]
I think the general approach is still sound - we will just need to poke a hole to allow for packages that only exist in binary form. My initial thought is either a new "requires_binary" setting, or some sort of annotation on the package (e.g. ":binary:pyside6"). I'd rather neither of these were needed... but then, I wish a lot of things about Linux packaging weren't true :-)

I may also need to spend some time with auditwheel to work out what it is doing to see if it's a universal problem, or something that only affects some packages (like Pillow).

The other approach to explore is conda. I don't know if conda does any processing similar to what auditwheel does in the default configuration; but in the extreme case, we could set up a custom channel that has packages built to Briefcase-compatible standards.

**Comment by freakboy3742** [comment]
I'm going to close this; it's not quite as simple as I first thought (at least in part because of the issue picked up by CI). The good news is that on further investigation, I think there's a "documentation only" solution.

**Pull request closed without merging**
