### PR TITLE
Revert "Respect and pass through `ANDROID_USER_HOME` and `ANDROID_AVD_HOME`"

### LINKED ISSUE #1688: `avdmanager` is not compatible with AVDs created by other instances of Android SDK or AVDs created by newer instances of Android SDK
### Describe the bug

The changes in https://github.com/beeware/briefcase/pull/1673 to respect `ANDROID_USER_HOME` and `ANDROID_AVD_HOME` modified how Briefcase finds existing AVDs from `emulator -list-avds` to `avdmanager list avd`. While this ostensibly works fine when all the AVDs are created by the Briefcase-managed Android SDK, there are issues when AVDs are created by other Android SDK instances.

`avdmanager` seems to be quite tied to the SDK it is running from; or, in the least, `avdmanager` doesn't consider the AVD valid if it can't find the AVD's system image in the SDK that `avdmanager` is running from.

Here, all the Pixel devices were created by the SDK that Android Studio uses and `avdmanager` is reporting that many of the AVDs have a missing system image. That's because their system image is located the SDK instance that Android Studio is using and not the Briefcase-managed SDK.
```console
❯ ~/.cache/briefcase/tools/android_sdk/cmdline-tools/9.0/bin/avdmanager list avd
Available Android Virtual Devices:
    Name: beePhone
  Device: pixel (Google)
    Path: /home/russell/.android/avd/beePhone.avd
  Target: Default Android System Image
          Based on: Android 12.0 (S) Tag/ABI: default/x86_64
    Skin: pixel_7_pro
  Sdcard: 512 MB

The following Android Virtual Devices could not be loaded:
    Name: Pixel_8_Pro_API_31
    Path: /home/russell/.android/avd/Pixel_8_Pro_API_31.avd
   Error: Google pixel_8_pro no longer exists as a device
---------
    Name: Pixel_3a_API_31
    Path: /home/russell/.android/avd/Pixel_3a_API_31.avd
   Error: Missing system image for Google Play x86_64 Pixel_3a_API_31.
---------
    Name: Pixel_6a_API_31
    Path: /home/russell/.android/avd/Pixel_6a_API_31.avd
   Error: Google pixel_6a no longer exists as a device
---------
    Name: Pixel_5_API_31
    Path: /home/russell/.android/avd/Pixel_5_API_31.avd
   Error: Missing system image for Google APIs x86_64 Pixel_5_API_31.
---------
    Name: Pixel_7a_API_34
    Path: /home/russell/.android/avd/Pixel_7a_API_34.avd
   Error: Google pixel_7a no longer exists as a device
```

Furthermore, though, `avdmanager` seems to have a real forward compatibility problem. This can be seen in running different versions of `avdmanager` within the same SDK.

Here is what 9.0 version of `avdmanager` says when I run it from the same SDK that Android Studio is using:
```console
❯ /opt/sdks/Android/sdk/cmdline-tools/9.0/bin/avdmanager list avd
Available Android Virtual Devices:
    Name: beePhone
  Device: pixel (Google)
    Path: /home/russell/.android/avd/beePhone.avd
  Target: Default Android System Image
          Based on: Android 12.0 (S) Tag/ABI: default/x86_64
    Skin: pixel_7_pro
  Sdcard: 512 MB
---------
    Name: Pixel_3a_API_31
  Device: pixel_3a (Google)
    Path: /home/russell/.android/avd/Pixel_3a_API_31.avd
  Target: Google Play (Google Inc.)
          Based on: Android 12.0 (S) Tag/ABI: google_apis_playstore/x86_64
    Skin: pixel_3a
  Sdcard: 512M
---------
    Name: Pixel_5_API_31
  Device: pixel_5 (Google)
    Path: /home/russell/.android/avd/Pixel_5_API_31.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 12.0 (S) Tag/ABI: google_apis/x86_64
    Skin: pixel_5
  Sdcard: 512M

The following Android Virtual Devices could not be loaded:
    Name: Pixel_8_Pro_API_31
    Path: /home/russell/.android/avd/Pixel_8_Pro_API_31.avd
   Error: Google pixel_8_pro no longer exists as a device
---------
    Name: Pixel_6a_API_31
    Path: /home/russell/.android/avd/Pixel_6a_API_31.avd
   Error: Google pixel_6a no longer exists as a device
---------
    Name: Pixel_7a_API_34
    Path: /home/russell/.android/avd/Pixel_7a_API_34.avd
   Error: Google pixel_7a no longer exists as a device
```
The 9.0 version of `avdmanager` seemingly can't interpret the AVDs for newer Pixel phones because when I run the latest version of `avdmanager` for that SDK, it can interpret them:
```console
❯ /opt/sdks/Android/sdk/cmdline-tools/latest/bin/avdmanager list avd
Available Android Virtual Devices:
    Name: beePhone
  Device: pixel (Google)
    Path: /home/russell/.android/avd/beePhone.avd
  Target: Default Android System Image
          Based on: Android 12.0 ("S") Tag/ABI: default/x86_64
    Skin: pixel_7_pro
  Sdcard: 512 MB
---------
    Name: Pixel_3a_API_31
  Device: pixel_3a (Google)
    Path: /home/russell/.android/avd/Pixel_3a_API_31.avd
  Target: Google Play (Google Inc.)
          Based on: Android 12.0 ("S") Tag/ABI: google_apis_playstore/x86_64
    Skin: pixel_3a
  Sdcard: 512M
---------
    Name: Pixel_5_API_31
  Device: pixel_5 (Google)
    Path: /home/russell/.android/avd/Pixel_5_API_31.avd
  Target: Google APIs (Google Inc.)
          Based on: Android 12.0 ("S") Tag/ABI: google_apis/x86_64
    Skin: pixel_5
  Sdcard: 512M
---------
    Name: Pixel_6a_API_31
  Device: pixel_6a (Google)
    Path: /home/russell/.android/avd/Pixel_6a_API_31.avd
  Target: Google Play (Google Inc.)
          Based on: Android 12.0 ("S") Tag/ABI: google_apis_playstore/x86_64
    Skin: pixel_6a
  Sdcard: 512M
---------
    Name: Pixel_7a_API_34
  Device: pixel_7a (Google)
    Path: /home/russell/.android/avd/Pixel_7a_API_34.avd
  Target: Google Play (Google Inc.)
          Based on: Android 14.0 ("UpsideDownCake") Tag/ABI: google_apis_playstore/x86_64
    Skin: pixel_7a
  Sdcard: 512M
---------
    Name: Pixel_8_Pro_API_31
  Device: pixel_8_pro (Google)
    Path: /home/russell/.android/avd/Pixel_8_Pro_API_31.avd
  Target: Google Play (Google Inc.)
          Based on: Android 12.0 ("S") Tag/ABI: google_apis_playstore/x86_64
    Skin: pixel_8_pro
  Sdcard: 512M
```

### Steps to reproduce

Using Briefcase from `main` branch, run `briefcase run android` after creating AVDs with Android Studio.

### Expected behavior

Briefcase should be able to load AVDs that were created by other instances of Android SDK.

Before #1673, the emulator could identify AVDs even if the SDK that Briefcase was using didn't contain the system image that AVD was using; after selecting the AVD, Briefcase will verify the system image is available in the SDK and download it if it's not found.

So, at least technically, Briefcase could try to download any missing system images before calling `avdmanager`....but this seems unnecessarily premature and wasteful. On top of this, though, even once you download the missing system image in to the SDK that Briefcase is using, version 9.0 of `avdmanager` still doesn't work with devices that are "too new".

**Ultimately, it seems quite necessary to revert #1673 and attempt to implement `ANDROID_USER_HOME` and `ANDROID_AVD_HOME` support using `emulator` somehow....just note all its issues documented in #1673...**

### Screenshots

_No response_

### Environment

- Operating System: Windows 11, pop os 22.04
- Python version: 3.12.2
- Software versions:
  - Briefcase: `0.3.18.dev104+g94a448ba` (doesn't affect released versions)

### Logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rmartin16**
## Changes
- Reverts beeware/briefcase#1673
- Closes #1688
- Reopens https://github.com/beeware/briefcase/issues/1665

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
PyGObject 3.48.0 was released 2 hours ago and is failing to build/install on Fedora 39 with Python 3.12.

potentially related: https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/488

**Comment by rmartin16** [comment]
While that PyGObject issue says "installing python3-setuptools" should resolve the issue, I think it only resolves it for users not using build isolation. When I add setuptools to `build-system.requires` in PyGObject's pyproject.toml, only then can I build it on Fedora 39.

**Comment by rmartin16** [comment]
Logged at https://gitlab.gnome.org/GNOME/pygobject/-/issues/622.

**Comment by rmartin16** [comment]
Confirmed fix in https://gitlab.gnome.org/GNOME/pygobject/-/merge_requests/302 addresses this issue.

They mentioned pushing out a new release for this....so, CI will pass once that release is out.

**Comment by rmartin16** [comment]
And resolved with PyGObject==3.48.1 release.

**Comment by rmartin16** [comment]
And now Flatpak builds are failing on PyGObject....have to look at that later...

**Review by freakboy3742 — APPROVED** [review]
Heh - looks like that my "do we want to have briefcase use it's own AVD HOME" comment on the original PR turned out to be prophetic...

**Comment by rmartin16** [comment]
> Heh - looks like that my "do we want to have briefcase use it's own AVD HOME" comment on the original PR turned out to be prophetic...

haha....well, not its own per se....just the same one that Android Studio would be using

Nonetheless, this means I definitely won't be able to run the emulator on that other device....although, my next limitation was RAM usage, soooo.... (and I only really cared about that since its the device I'm bringing to pycon). Running one remotely and windowless should still work fine.

**Pull request merged**
