### PR TITLE
Correct some markup errors in docs.

### PR DESCRIPTION
**Pull request by freakboy3742**
Doing a local build of docs, I noticed some non-critical warnings and typographical inconsistencies. 

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
Related to this....I've been curious if you might be interested in adding these types of checks to CI.

For instance:
```
cd docs
sphinx-build -v -W --keep-going -E -a -b linkcheck . "build"
sphinx-build -v -W --keep-going -E -a -b html . "build"
```

**Comment by freakboy3742** [comment]
Definitely interested - anything we can do to prevent easily avoided errors is a win in my book.

**Review by rmartin16 — APPROVED** [review]
I'm good with this. I've also incorporated it in to #1168.

**Comment by freakboy3742** [comment]
Ah - I missed that you'd built your PR on top of this one. I'll close this one.

**Pull request closed without merging**
