### PR TITLE
Bump tox from 4.10.0 to 4.11.0

### PR DESCRIPTION
**Pull request by rmartin16**
## Changes
- `tox` is failing RTD builds for some reason; bump to 4.11.0

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
In case #1360 doesn't merge very soon....let's merge this to fix this RTD build issue.

**Review by freakboy3742 — APPROVED** [review]
Very weird... 4.10 builds were working fine 2 days ago when I merged the dependabot change... and there's nothing in the 4.11 release notes about a bug fix. I can only assume there's something pinned differently in tox's dependencies? 

This PR looks good; I'll hold off merging it until I've reviewed #1360 (which is next on my list). If I can merge that, then there's a little less commit churn.

**Comment by rmartin16** [comment]
> This PR looks good; I'll hold off merging it until I've reviewed #1360 (which is next on my list). If I can merge that, then there's a little less commit churn.

Good deal; this PR is only a contingency plan.

> Very weird... 4.10 builds were working fine 2 days ago when I merged the dependabot change... and there's nothing in the 4.11 release notes about a bug fix. I can only assume there's something pinned differently in tox's dependencies?

The failure is happening on the `wheel` install:
```
.pkg: install_requires_for_build_editable> python -I -m pip install wheel
docs-lint: internal error
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/session/cmd/run/single.py", line 46, in _evaluate
    tox_env.setup()
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/api.py", line 248, in setup
    self._setup_with_env()
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/runner.py", line 145, in _setup_with_env
    self._setup_pkg()
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/runner.py", line 168, in _setup_pkg
    self._packages = self._build_packages()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 119, in _build_packages
    packages = package_env.perform_packaging(self.conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/package.py", line 45, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 189, in perform_packaging
    deps = self._load_deps(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/package.py", line 45, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 248, in _load_deps
    deps = self._load_deps_from_built_metadata(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/package.py", line 45, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 292, in _load_deps_from_built_metadata
    reqs = self.get_package_dependencies(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/package.py", line 45, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 300, in get_package_dependencies
    self._ensure_meta_present(for_env)
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/package.py", line 45, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/briefcase/envs/1425/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 321, in _ensure_meta_present
    dist_info = hook(self.meta_folder, self._wheel_config_settings).metadata
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'metadata'
```

Given the reference to "config_settings", I'm thinking it might be this...???
- https://github.com/tox-dev/tox/pull/3090

**Comment by freakboy3742** [comment]
> > This PR looks good; I'll hold off merging it until I've reviewed #1360 (which is next on my list). If I can merge that, then there's a little less commit churn.
> 
> Good deal; this PR is only a contingency plan.

I've just approved that PR; once CI finishes, I'll merge - so I'll close this PR.

> * [Add config_settings support for build backend calls tox-dev/tox#3090](https://github.com/tox-dev/tox/pull/3090)

Yeah - but wheel, setuptools, virtualenv or build haven't had a release since Monday... I'm at a loss for what has changed that has caused 4.10 builds to *stop* working. 

Anyway - 4.11 builds are working, so it's a moot point.

**Pull request closed without merging**
