### PR TITLE
Added support for upgrading and recompiling an application before packaging it. 

### PR DESCRIPTION
**Pull request by ekdnam**
add_options() function has been added to the `package.py` script in `src\briefcase\commands`. The changes made have been mentioned in `changes\473.package.rst`.

the command `briefcase package -u` can now run perfectly, compared to before, when it resulted in an error.

Issue: 473 - [briefcase package -u returns unrecognized arguments: -u](https://github.com/beeware/briefcase/issues/473)

## PR Checklist:

- [`x`] All new features have been tested
- [`x`] All new features have been documented
- [`x`] I have read the **CONTRIBUTING.md** file
- [`x`] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — COMMENTED** [review]
Regarding the towncrier failure: You've got the right idea, but you're slightly off with the implementation. The name between the number and `.rst` is the type of change - that means `bug`, `feature`, `docs` or `misc`. In this case, it's probably `feature`, since it's a completely new capability that has been added.

**Comment by ekdnam** [comment]
Okay got it! Have made the required changes. Thanks!

**Comment by ekdnam** [comment]
Do some tests need to be added for the changes made to `src/briefcase/commands/package.py`?

**Comment by freakboy3742** [comment]
@ekdnam Yes - that's what the codecov test failure is telling you: there is new functionality, but it's untested. The existing tests for the `-u` option on other commands should give you a model for what is required.

**Comment by ekdnam** [comment]
Okay, will add the required tests

**Comment by freakboy3742** [comment]
This PR has been extended in #695, adding the missing tests.

**Pull request closed without merging**
