### PR TITLE
Support defining an msi installer scope as "per machine"

### LINKED ISSUE #498: Winows: installation per-machine over per-user
At the moment, when packaging an MSI using Briefcase, the installation is **per-user**. I need to have the ability to make the installation **per-machine**.

Right now, the program is currently installed in the %appdata% folder - which is a per-user folder. the env variable translates into something that includes the username in it, and because we are deploying to "fresh" installs - no users have logged in yet. I want to be able to install the program regardless of whether the user that is going to use the program is logged in or not - so in the very least, the program needs to be installed in the "program files" folder.

### PR DESCRIPTION
**Pull request by saroad2**
Now users can define an MSI installer to be "per user" or "per machine".

Fixes #498

## PR Checklist:

- [X] All new features have been tested
- [ ] All new features have been documented
- [X] I have read the **CONTRIBUTING.md** file
- [X] I will abide by the code of conduct

### CODE REVIEW

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
Looks good; but needs a test to make sure the attribute is picked up correctly.

**Review by freakboy3742 — CHANGES_REQUESTED** [review]
I was about to merge this, and it occurred to me that we're not doing any error handling on the user-provided value for `install_scope`. WiX will only accept `perUser` and `perMachine` as valid values. At the very least, we should be validating that the user-provided value is in the right format; however, I also wonder whether the setting that Briefcase exposes should be a boolean. Is there any other valid option? Should we simplify the interface to `system_installer=True` (or similar)?

**Comment by saroad2** [comment]
You are absolutely correct, and I like the name `system_installer`. In the following days, I'll make the change in https://github.com/beeware/briefcase-windows-msi-template and change this PR accordingly.

**Comment by freakboy3742** [comment]
I actually think the _template_ is fine - after all, it specifies the text that will be directly injected into the template. However, if you feel it's worth keeping the template in alignment with the pyproject config option, I won't object.

**Comment by saroad2** [comment]
In the end, I came to the conclusion to keep the template as it is and only change the code here.

**Review by freakboy3742 — APPROVED** [review]
👍 I've pushed some minor tweaks (including docs), but otherwise this is good to go!

**Pull request merged**
